---
title: "Certifications"
---

## 2022
- Sertifikasi A
- Sertifikasi B

## 2021
### Course
n/a

### Workshop
Pelatihan Penulisan Artikel Populer. Held by Direktorat Publikasi Ilmiah dan Informasi Strategis, IPB University. Taken on Zoom. Issued November 2021. [see credential](https://drive.google.com/file/d/1TOWvaSbgTstYVNnFHKxLjMyaEfkTIGdX)

Workshop Bioinformatika: Network Pharmacology. Held by PUI-PT Pusat Studi Biofarmaka Tropika LPPM IPB University. Taken on Zoom. Issued May 2021. [see credential](https://drive.google.com/file/d/1i3v89EgzdPjYFdjk26anxLOz9EUlemi2)

### Module
n/a

### Symposium
n/a

### Seminar
Stepping into Precision Medicine Era in Cancer. Held by Department of Pharmacology & Therapy; Faculty of Medicine, Public Health and Nursing; Universitas Gajah Mada. Taken on Zoom. Issued November 2021. [see credential](https://drive.google.com/file/d/1LpQ4Ih3wKK7csbPdX54frpr4AWAo5ii-)

The 33rd IPB Strategic Talk: Reorientasi Ekonomi Indonesia Berbasis Nusantaranomics Menuju Masyarakat yang Berkeadilan Sosial. Held by Direktorat Publikasi Ilmiah dan Informasi Strategis, IPB University. Taken on Zoom. Issued November 2021. [see credential](https://drive.google.com/file/d/1AYnoQWksdE_HcVaGZQCcBu_2qIahYl63)

TropBRC Webinar Series #6: Trend Riset Metabolomik dalam Pengembangan Produk Biofarmaka. Held by PUI-PT Pusat Studi Biofarmaka Tropika LPPM IPB University in collaboration with Himpunan Kimia Indonesia, Klaster Riset Metabolomik AR-Lab IPB, and Forum Metabolomik Indonesia. Taken on Zoom. Issued July 2021. [see credential](https://drive.google.com/file/d/1o3vIUAttcvtelfYo-2d2j94i5LidEPGO)

1st Webinar of Enzyme Series: Current and Future Trends in Enzyme Technology and Its Application. Held by PUI Biorefineri Terpadu, Puslit Bioteknologi Lembaga Ilmu Pengetahuan Indonesia (LIPI) in collaboration with Badan Riset dan Inovasi Nasional (BRIN). Taken on Zoom. Issued June 2021. [see credential](https://drive.google.com/file/d/1sXAjZu6djFH9CmWh97IxbwS6UjGMJtD1)

TropBRC Webinar Series #4: Potensi Sumber Daya Hayati Indonesia sebagai Sumber Biofarmaka. Held by PUI-PT Pusat Studi Biofarmaka Tropika LPPM IPB University. Taken on Zoom. Issued June 2021. [see credential](https://drive.google.com/file/d/13v1QcoAWG8d6MJ0bJY3zImOifDIcOlgO)

Rodent Anesthesia from Start to Finish. Held by Asosiasi Dokter Hewan Praktisi Hewan Laboratorium Indonesia (ADHPHLI), Perhimpunan Peneliti dan Pengguna Hewan Laboratorium Indonesia (P3HLI) and Perhimpunan Dokter Hewan Indonesia (PDHI) Cabang Jawa Barat II. Taken on Zoom. Issued April 2021. [see credential](https://drive.google.com/file/d/1AFYqFIuoRddV1dO8LtpzwwFIK2udm7ds)

Webinar Series #1 Perhipba: Kekayaan Sumber Hayati Obat Herbal. Held by Perhimpunan Peneliti Bahan Alam (Perhipba) in collaboration with PUI-PT Pusat Studi Biofarmaka Tropika LPPM IPB University, and PUI PT Nutrasetikal-Pusat Penelitian Biosains dan Bioteknologi ITB. Taken on Zoom. Issued March 2021. [see credential](https://drive.google.com/file/d/1PbUlYu1FlcaiPKR3h7CIbXUPMfY5oLeF)

Perhitungan Jumlah Sampel pada Penelitian dengan Hewan Coba. Held by Asosiasi Dokter Hewan Praktisi Hewan Laboratorium Indonesia (ADHPHLI), Perhimpunan Peneliti dan Pengguna Hewan Laboratorium Indonesia (P3HLI) and Perhimpunan Dokter Hewan Indonesia (PDHI) Cabang Jawa Barat II. Taken on Zoom. Issued March 2021. [see credential](https://drive.google.com/file/d/1yAlkawhLVudPPWdL81gl8a8PE28UcoNj)

## 2020
### Course
Pengelolaan Fasilitas Hewan Penelitian dan Pengujian (Tikus dan Mencit). Held by Pusat Studi Satwa Primata – LPPM IPB in collaboration with Asosiasi Dokter Hewan Praktisi Hewan Laboratorium Indonesia (ADHPHLI), Perhimpunan Peneliti dan Pengguna Hewan Laboratorium Indonesia (P3HLI) and Perhimpunan Dokter Hewan Indonesia (PDHI) Cabang Jawa Barat II. Taken on Zoom. Issued October 2020. [see credential](https://drive.google.com/file/d/1TB6I8ju0zCYn1r84vYoLkAhOSbyZJf6V)

Aromatherapy: Clinical Use of Essential Olis. Held by University of Minnesota. Taken on Coursera. Issued September 2020. [see credential](https://www.coursera.org/account/accomplishments/verify/K2SCAFKGZQFY)

Perfect Tenses and Modals. Held by University of California, Irvine. Taken on Coursera. Issued September 2020. [see credential](https://coursera.org/share/6e3b1b0ee421403324fe9fb3270f3ea1)

Penggunaan Tikus dan Mencit dalam Pengujian dan Penelitian. Held by Pusat Studi Satwa Primata – LPPM IPB in collaboration with Asosiasi Dokter Hewan Praktisi Hewan Laboratorium Indonesia (ADHPHLI), Perhimpunan Peneliti dan Pengguna Hewan Laboratorium Indonesia (P3HLI) and Perhimpunan Dokter Hewan Indonesia (PDHI) Cabang Jawa Barat II. Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/190Nu6r8fxSOwmJxcC_ehT7SOjZyVdtN5)

Introduction to Philosophy. Held by The University of Edinburgh. Taken on Coursera. Issued July 2020. [see credential](http://coursera.org/verify/8NVWDLQP24QP)

Drug Discovery. Held by University of California San Diego (UC San Diego). Taken on Coursera. Issued June 2020. [see credential](https://coursera.org/share/6d7891aa16fc892126be22b82292adc5)

Covid-19 Contact Tracing. Held by The John Hopkins University. Taken on Coursera. Issued May 2020. [see credential](https://www.coursera.org/account/accomplishments/verify/9BRCH8LY8QVT)

### Workshop
Web Training: Penulisan Artikel Ilmiah Populer di Media Massa. Held by Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued November 2020. [see credential](https://drive.google.com/file/d/1BIyuAz32ZaliN36Ob2JFmLSgIccl46JG)

Workshop Kurikulum Merdeka untuk Pengembangan Bioteknologi Sumber Daya Hayati Indonesia. Held by Program Studi Bioteknologi, Departemen Biologi, Fakultas Sains dan Matematika, Universitas Dipenegoro (UNDIP). Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1nTvaKbuwu7wS26YIx226L2B9D86jnpaZ)

Webinar Workshop Online Publikasi di Jurnal Internasional Bereputasi Menengah dan Tinggi. Held by Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1C9x7ai0DhjAxkjLTqQvoI3Cj4fUch-mb/)

Virtual Workshop on International Standard Paper Writing and Publication. Held by IEEE Indonesia Section. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1Yc9wDzMAd_vb_y-pj5QM_tXXNOpjeEBo)

### Module
Structuring Your Article Correctly. Held by Researcher Academy, Elsevier. Taken on Researcher Academy. Issued August 2020. [see credential](https://drive.google.com/file/d/13pbU91ECr4APsWxl9sJrj5z5zP-POkd5)

How to Prepare Your Manuscript. Held by Researcher Academy, Elsevier. Taken on Researcher Academy. Issued July 2020. [see credential](https://drive.google.com/file/d/1p7ZnCePJv-l8oNuFC30thwLCk6pDnFin)

### Symposium
Simposium Kopi Nasional: Semangat Mengangkat Kopi Nasional di Masa Pandemi Covid-19. Held by Asosiasi Eksportir dan Industri Kopi Indonesia (AEKI) Kontes Kopi Spesialti Indonesia. Taken on Zoom. Issued October 2020. [see credential](https://drive.google.com/file/d/1pP-Et86vbYqhXG7pMmWPKC0ZnA3AdIIc)

### Seminar
LIPI-Springer Publishing Forum 2020. Held by Balai Media dan Reproduksi (LIPI Press). Taken on Zoom. Issued November 2020. [see credential](https://drive.google.com/file/d/1aoqpkvi89WPqnYp3MCGk46BjIgEiT6B_)

Teknologi Probiotik dan Aplikasinya di Industri Pangan. Held by Pusat Studi Pangan dan Gizi Universitas Gadjah Mada. Taken on Zoom. Issued November 2020. [see credential](https://drive.google.com/file/d/197tew_ZtVRS4sFSgsJ6YiYI-t5Un7iGj)

Vaksin dan Herbal: Bisakah Disandingkan?. Held by Komite Pananganan COVID-19 dan Pemulihan Ekonomi Nasional (KPCPEN), Kementerian Komunikasi dan Informatika (KOMINFO), and SIBERKREASI. Taken on Zoom. Issued November 2020. [see credential](https://drive.google.com/file/d/1qBChn7KX0Osu5S4buNtQkUoprpqPtgcw)

Diskusi Interaktif Online: Platform Riset dan Inovasi. Held by Energy Academy Indonesia, Atase Perindustrian KBRI Brussels and Ikatan Alumni ITB Komisariat Eropa. Taken on Youtube. Issued October 2020. [see credential](https://drive.google.com/file/d/1muuc6Z4Z8K5aX5I6JiQxVo4ZyITVVnWK)

UMT – Indonesia Universities Joint Webinar on Science Topic: Natural Resources as a Potential Agent for Covid-19 Prevention. Held by Institute of Marine Biotechnology and Universiti Malaysia Terengganu. Taken on Zoom. Issued October 2020. [see credential](https://drive.google.com/file/d/1rFNJaXZ9nYLFoPvVIZ8u8cF2AWkt3fzK)

Hilirisasi dan Komersialisasi Produk Pangan Fungsional dan Nutrasetikal Basis Riset Perguruan Tinggi dan Industri. Held by Perhimpunan Penggiat Pangan Fungsional dan Nutrasetikal Indonesia (P3FNI). Taken on Zoom. Issued October 2020. [see credential](https://drive.google.com/file/d/1zwlCsM8MHcCSg-QykZqXla1hjFT-aiGK)

Salam Berbagi #3: Policy and Strategy for Innovation in Digital Business and Technology towards Indonesia 2045. Held by Institut Teknologi Bandung (ITB). Taken on Zoom. Issued September 2020. [see credential](https://drive.google.com/file/d/1pYVq4pC25SjfmH-HX3uQ2Mn6kjBtKPYN)

Nutraceutical for Human Health. Held by Bioscience and Biotecnology Research Center – ITB. Taken on Zoom. Issued September 2020. [see credential](https://drive.google.com/file/d/1VP3JluUZw0RLevfUdOQotmzBggF73QMH)

Hilirisasi Hasil Riset dan Inovasi ke Dunia Industri. Held by Ikatan Alumni Institut Teknologi Bandung (IAITB) Komisaritat Eropa in collaboration with Atase Perindustrian KBRI Brussels and Energy Academy Indonesia (ECADIN). Taken on Zoom. Issued September 2020. [see credential](https://drive.google.com/file/d/1H4mn8C3KPzimISpDKDNV1lUm6IOgMAKH)

Sinergi antara Akademik, Pelaku Usaha dan Pemerintah dalam Hilirisasi Hasil-Hasil Penelitian Berbasis Fitofarmaka. Held by Pusat Studi Fitofarmaka, Universitas Kristen Satya Wacana (UKSW). Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/1pAYq1X5jLxbKqlDT2jBqmfuw0BPsX_ib)

Penggunaan Hewan Coba dalam Studi COVID-19: Pertimbangan Pemilihan Hewan Model dan Aspek Biosafety. Held by Asosiasi Dokter Hewan Praktisi Hewan Laboratorium Indonesia (ADHPHLI) in collaboration with Perhimpunan Dokter Hewan Indonesia (PDHI) Cabang Jawa Barat II. Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/1LzrdpQvY-Vsx1U_LHctcmcjQD_MXuUdd)

Ensuring Reliable & Reproducible Results Everytime through Optimized Sample Preparation Workflows. Held by Berca Niaga Medika [Instrument Solution Group (ISG)]. Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/1W_KBEHicMJNp-qNLRH-_RJf4gDSowZGK)

Thee Kian Wie V Lecture Series: Kebijakan Pembangunan yang Inklusif dan Berkelanjutan: Strategi Pemulihan Pasca Pandemi. Held by Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/13IetRdxWiIikTouiuQgpQlZL0cRIsP09)

East Indonesia Seas as a Global Epicentre of Marine Biodiversity. Held by Pusat Penelitian Laut Dalam, Lembaga Ilmu Pengetahuan Indonesia (LIPI) in collaboration with Ikatan Sarjana Oseanologi Indonesia (ISOI) Komda Ambon. Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/1kiHyaR1-WNmp6RUw6Uit5xtCoQ01_atv)

MIPAtalk Series 9: The Value of Science and The Role of Experts in Crisis Situations. Held by FMIPA Universitas Indonesia. Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/1oweHJXP6BKQgQ4u4sM3A2Pku2g7VSe6z)

Mendongkrak Kinerja Pengabdian kepada Masyarakat. Held Perhimpunan Dokter Hewan Indonesia Organisasi Non Teritorial Asosisasi Parasitologi Veteriner Indonesia. Taken on Zoom. Issued August 2020. [see credential](https://drive.google.com/file/d/1AkPfo5XUIl9IAfVEqvQQkEGtm_VBvZ6L)

Kelas Umum Pandemi 6 “Perjalanan Covid 19 di Indonesia: Dari Tes hingga Vaksin” dengan Pembicara Prof. Herawati Sudoyo. Held by Lapor Covid-19. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/10euPqKOECI0y-XP0tT0poUvtdii7Z_qp)

Pemanfaatan Bahan Alam di Bidang Kosmetik Kesehatan (Cosmeceutical). Held by Balai Besar Kimia dan Kemasan Kementerian Perindustrian Republik Indonesia. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1kcQjy1USadR70QH2lSIyiHxCNWCUGujV)

Guest Lecture: From Idea to Drug Development by Prof. Dr. Med. Markus Meyer, Professor at Hannover Medical School, Germany. Held by Doctoral Program in Medical Sciences. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/15xLFNDv4XAxnRgGwMXutRPojw0VS60YS)

Seminar Online Biologi Tumbuhan. Held by Departemen Biologi, Institut Pertanian Bogor (IPB). Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1U1nTbKpvjpA24FEHidRJZIyuH2rotvuy)

Webinar Bedah Buku: Margarin Kelapa Sawit dan Fortifikasinya untuk Peningkatan Kesehatan. Held by Dakara Bisnis Institut (DBI) Publishing. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/10vOsVsqatdAKa2lie2xoznlK5zMjQ9Yx)

Valorisasi dan Strategi Bisnis Inovatif Minyak Atsiri. Held by Agroteknologi & Bioproduk SITH ITB in collaboration with Bio-N Oils and Bioengineering ITB. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/18JjTMWi25dXBTsiybR8_UFgmp9cKqX-V)

Webinar Series Keamanan Pangan 4: Kupas Tuntas Listeria monocytogenes dan Penyakit via Makanan Lainnya. Held by Pusat Studi Pangan dan Gizi Universitas Gadjah Mada (UGM) in collaboration with Asosiasi Profesi Keamanan Pangan Indonesia (APKEPI). Taken on Cisco Webex. Issued July 2020. [see credential](https://drive.google.com/file/d/1ctRUCahmACOHg5FKjFqgXxrDqDCzGuw9)

Current Trends of Coffee Technology: Challenge and Opportunity. Held by Southeast Asian Food & Agricultural Science & Technology (SEAFAST) Center, Lembaga Penelitian dan Pengabdian kepada Masyarakat – Institut Pertanian Bogor (IPB). Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1PIFCOdqt1PxJSg0ULG42sbwrz6EM2ph3)

Webinar Series #3 PUI-PT Ketahanan Pangan (Inovasi Pangan Lokal) UNTIRTA: Memaksimalkan Komoditi Khas Lokal dalam Hilirisasi Riset di Masa Pandemi Covid-19. Held by Universitas Sultan Ageng Tirtayasa. Taken on Zoom. Isssued July 2020. [see credential](https://drive.google.com/file/d/1AWQifEX_SRUo8tdegZw2yW6XVykAN3ZL)

Awareness Penjaminan Mutu Pengujian berbasis ISO/IEC 17025:2017. Held by PT Global Scholarship Services Indonesia, Institut Pertanian Bogor (IPB). Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1aKpGj8kTUh98kCr-NKtxGPWGkTNtLs_Z)

Webinar Understanding Scopus Best Practices-in collaboration with Universitas Indonesia. Held by Researcher Academy, Elsevier in collaboration with Universitas Indonesia. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1IL27uSJmLkPxhj_wCT7dUNAFWUHJrX5D)

Maintaining International Bonding: Learning from Partner Universities. Held by IPB University in collaboration with Tokyo University of Agriculture and Australian National University. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1ZVyXEVHn2fAM1eVXTR_gnwk_jADptOX1)

Ibu Kota Negara (IKN) Inklusif: Telaah Aspek Sosial dan Lingkungan Hidup dalam (Proses) Perencanaan Pembangunan. Held by Pusat Penelitian Kependudukan, Lembaga Ilmu Pengetahuan Indonesia (LIPI) in collaboration with Pengurus Nasional Ikatan Ahli Perencanaan Indonesia. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1dHi-594qcgkytsy0pRHICLQ_-xyC-86e)

Seri Webinar TropBRC: Budidaya Tanaman Obat. Held by Pusat Studi Biofarmaka Tropika, IPB University. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/15HpMrZLKlqgXTAsKwfJLZ99O-HP24tpH)

FMIPA UI Series 6: The Value of Science and The Role of Experts in Crisis Situations. Held by FMIPA Universitas Indonesia. Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1iq3PiNYxNHhEJVpU-lcsHc94rFA7KpaK)

Kesiapan Teknologi dan Pemanfaatannya untuk Mendukung Stabilitas Ketersediaan Minyak Nilam. Held by Balai Penelitian Tanaman Rempah dan Obat (Balittro). Taken on Zoom. Issued July 2020. [see credential](https://drive.google.com/file/d/1JIqaxSoRe-W0patPujCDvwZzyUOFYdzl)

Menyikapi Transfer Material Virus, Untung atau Buntung. Held by Biro Kerja Sama, Hukum dan Humas Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1VnnrCQo0JveDH2UL22sPpJFVfz8wLiV7)

Webinar Series 3 Komite Etik Penelitian Kesehatan FKUI RSCM Bersama ICTEC RSCM FKUI: Etika Penelitian Pada Pandemi Covid-19. Held by Indonesian Clinical Training & Education Center (ICTEC) in collaboration with Komite Etik Penelitian Kesehatan FKUI RSCM and Forum of Indonesian Recognized Research Ethics Committee Faculty of Medicine Universitas Indonesia (FIRREC). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1cU2VdFspExapr7VVSnCJDYxiXbd0OlRH)

SATUPENATalk Sesi 4: Lingkungan Hidup, Budaya, Hukum pada Masa Wabah Corona. Held by SATUPENA in collaboration with Balai Pustaka. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1KgWgLICl9huBNp6nuZJqzBjy86uGlOSR)

Konsorsium Bioteknologi Indonesia dan Badan Standardisasi Nasional Berbagi Ilmu; WEBINAR Seri 3: (1) Uji Ketahanan Bahan Tekstil APD (Hamzat) terhadap Penetrasi Mikroba Sesuai Standar EN 14126, (2) Perbandingan Hasil Inovasi Karya Anak Bangsa untuk Deteksi Rapid Test IgG/IgM dan Swab Test PCR SARS Cov2. Held by Konsorsium Bioteknologi Indonesia (KBI) in collaboration with Badan Standardisasi Nasional (BSN) and PT ITS Science Indonesia. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1VArAXHG9Kz8pUW1AQ81wa7IFIOQwkdYP)

Series 1: Kurikulum Merdeka Belajar Sarjana Farmasi. Held by Faculty Mathematics and Natural Sciences Universitas Negeri Semarang. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1vmievDStdsqcBvD9tZOX2FF0SJXltBmu)

FMIPA UI Webinar Series 5: The Value of Science and The Role of Experts in Crisis Situations. Held by FMIPA Universitas Indonesia. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1rZBqTO8CZBP-3mPSgH6C7Q8ADZvZGdJF)

Narkoba dan Pandemi Covid-19; Mengkaji Penyalahgunaan Narkoba dari Aspek Komorbiditas dan Watak Virus Covid-19 untuk Kesehatan secara Holistik. Held by Ikatan Alumni Universitas Indonesia (ILUNI UI) in collaboration with Badan Narkotika Nasional Republik Indonesia (BNN RI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1aqq5kTqFRgOXCkZTxv-kiJ9QOJYoGEGF)

Telemedicine: Now or Never. Held by Telkom University in collaboration with HMTI-1994. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1WqPIVWX-1yiQJHfleke1ZL4FUXSq3S5m)

FMIPA UI Webinar Series 4: Peluang Riset Fisika Teori di Era Pandemik COVID-19. Held by FMIPA Universitas Indonesia. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1CNINnQS9YOiPmwnS5Nm825-yfoHJ3n-y)

SATUPENATalk Sesi 3: Pendidikan, Ekonomi & Politik pada Masa Wabah Corona. Held by SATUPENA in collaboration with Balai Pustaka. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1bFEVyxmCwtYutraSTqbb7o0-s_k_dPX_)

Seri Inspirasi Ilmuwan: Membangun Masa Depan Indonesia dengan Riset Nanoherbal. Held by Nano Central Indonesia (NCI) in collaboration with Masyarakat Nano Indonesia (MNI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1FsmvgWOAMLhlB1MRViiP2WF1k-oB-ush)

FMIPA UI Webinar Series 3: The Value of Science and The Role of Experts in Crisis Situations. Held by FMIPA Universitas Indonesia. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1S02BJh_raC-xhWHf_hUn9cgExxEamNrr)

Peran TRO Ditengah Pandemic Covid 19. Held by Balai Penelitian Tanaman Rempah dan Obat (Balittro). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1nh7uNNrJqqoQYOPmwpHsfgVVLyZal0qs)

SATUPENATalk Sesi 2: Sains, Sastra & Kepemimpinan pada Masa Wabah Corona. Held by SATUPENA in collaboration with Balai Pustaka. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/18PzEEOCmdMThLxtH4hljPCE9niNnCNJ8)

Ngaji Teknologi LIPI Jogja 1: Penanganan Produk Kurban di Masa Pandemi. Held by Balai Penelitian Teknologi Bahan Alam, Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1hMZP1TWB6vZ0uzSM05M_qSY-K2IaId9p)

Webinar PP IAKMI: Genomics and Vaccine Development. Held by Pengurus Pusat Ikatan Ahli Kesehatan Masyarakat Indonesia (PP IAKMI) in collaboration with Ikatan Ahli Kesehatan Masyarakat Indoensia Cyber University (IAKMI Cyber University). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1ecmTs90FH9gffTTiP6VvXb_5CLD12SvM)

Talk to Scientist: Riset Kimia dan Fisika LIPI Cegah Covid-19. Held by Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1CxJxnY5XQ9LgrMdl8P9T_TKsbz6mqhyo)

Seri Webinar TropBRC: Strategi Modernisasi Jamu dalam Menghadapi Kenormalan Baru. Held by Pusat Studi Biofarmaka Tropika, IPB University. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1kINAEth65hoq_hnDGnDZiF9_Hdfl3H7C)

International Webinar Conference: Food and Immune System During Covid-19 Pandemic. Held by Undergraduate Program of Food Technology, Institut Teknologi Sumatera (ITERA) in collaboration with Indonesia Association of Food Technologist (PATPI) Lampung. Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1qozeHA8tgaGLEYjjJKXQD7iLm5NpP8LQ)

Konsorsium Bioteknologi Indonesia dan Badan Standardisasi Nasional Berbagi Ilmu; WEBINAR Seri 1: (1) Pengembangan Propolis Indonesia sebagai Obat Herbal Covid-19, (2) Pengembangan Rapid Diagnostik Kit untuk Covid-19. Held by Konsorsium Bioteknologi Indonesia (KBI) in collaboration with Badan Standardisasi Nasional (BSN). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/13xdSYlW1lf6INHSlBDz9TpkPmxmPx8dm)

Seri Inspirasi Ilmuan: Membangun Masa Depan dengan Riset Material dan Mobil Listrik. Held by Nano Center Indonesia (NCI) in collaboration with Masyarakat Nano Indonesia (MNI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1oeBKghlm4lOVZePJXkyUXnXGtpOuQp4x)

Ambassador Talk with Scientist: Diplomacy in the Time of Global Pandemic. Held by Kementrian Riset dan Teknologi / Badan Riset Inovasi Nasional Republik Indonesia in collaboration with Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/1dvgaNu_fhISAb31hly6nl_8vYJHDI0b4)

The 8th Webinar Series IMERI 2020: Bioinformatics Analysis Provides Insight for COVID-2019 Research. Held by Bioinformatics Core Facilities Cluster in collaboration with Center of e-Learning Cluster Indonesian Medical Education and Research Institute (IMERI), Faculty of Medicine Universitas Indonesia (FMUI). Taken on Zoom. Issued June 2020. [see credential](https://drive.google.com/file/d/14Q4tEt6GqSqPneciaeHR5JIOZIfZZuNo)

Quality Learning and Assessments During the Covid-19 Pandemic. Held by Southeast Asia Minister of Education Organization (SEAMEO). Taken on Youtube. Issued May 2020. [see credential](https://drive.google.com/file/d/1lqMzcuZPrvE6-Cnla1ZavK2slfXzsRxS)

Biodiversitas Nusantara. Held by Pusat Penelitian Biologi, Kedeputian Ilmu Pengetahuan Hayati, Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued May 2020. [see credential](https://drive.google.com/file/d/15DRMXmsFPmH43lDgDlFvNCvWDsXGSx3l)

Talk to Scientists: Bekerja di Masa Pandemi Versi LIPI. Held by Lembaga Ilmu Pengetahuan Indonesia (LIPI). Taken on Zoom. Issued May 2020. [see credential](https://drive.google.com/file/d/1-oNO9gKkoJ1CDvm6c_bEqgLgfmUHlHsB)

Melakukan Riset dan Membangun Virtual Laboratorium di Tengah Masa Pandemik Covid-19. Held by Fakultas Ilmu Komputer Universitas Indonesia in collaboration with IEEE Indonesia Section. Taken on Zoom. Issued May 2020. [see credential](https://drive.google.com/file/d/1GWmNFDu76b5w5QW9RZTkhOmlDMpAVzti)
